<?php

/**
 * Test class for S2AnA_AuthenticationContextResolverImpl.
 * Generated by PHPUnit2_Util_Skeleton on 2007-02-05 at 22:05:42.
 */
class S2AnA_AuthenticationContextResolverImplTest extends PHPUnit2_Framework_TestCase
{
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        $suite  = new PHPUnit2_Framework_TestSuite("S2AnA_AuthenticationContextResolverImplTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetContainer().
     */
    public function testSetContainer()
    {
    }

    /**
     * @todo Implement testResolve().
     */
    public function testResolve()
    {
    }
}

?>