<?php

/**
 * Test class for S2AnA_AuthenticatedAccessOnlyInterceptor.
 * Generated by PHPUnit2_Util_Skeleton on 2007-02-05 at 22:05:42.
 */
class S2AnA_AuthenticatedAccessOnlyInterceptorTest extends PHPUnit2_Framework_TestCase
{
    private $_authAccessOnlyObject = NULL;
    
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        $suite  = new PHPUnit2_Framework_TestSuite("S2AnA_AuthenticatedAccessOnlyInterceptorTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $container = S2ContainerFactory::create(APP_DICON);
        $this->_authAccessOnlyObject = $container->getComponent('authAccessOnly');
        
        global $userPrincipal;
        $userPrincipal = NULL;
        global $authenticated;
        $authenticated = FALSE;
        global $inRoles;
        $inRoles = array();
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
        $this->_authAccessOnlyObject = NULL;

        global $userPrincipal;
        $userPrincipal = NULL;
        global $authenticated;
        $authenticated = FALSE;
        global $inRoles;
        $inRoles = array();
    }

    public function testNotAuthenticated()
    {
        global $authenticated;
        $authenticated = FALSE;
        try {
            $this->_authAccessOnlyObject->call();
            $this->fail();
        } catch(S2AnA_NotAuthenticatedException $e) {
            $this->assertTrue(TRUE);
        } catch(Exception $e) {
            $this->fail();
        }
    }
    
    public function testAuthenticated()
    {
        global $authenticated;
        $authenticated = TRUE;
        try {
            $this->_authAccessOnlyObject->call();
            $this->assertTrue(TRUE);
        } catch(S2AnA_NotAuthenticatedException $e) {
            $this->fail();
        } catch(Exception $e) {
            $this->fail();
        }
    }
}

?>